### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [eliasgranderubio/bidDB_downloader#1]
Hi!
we are building a free and open aggregated vulnerabilities DB at https://github.com/nexB/vulnerablecode and we code in Python... so reusing your fine code would only make sense. What would be the license for this ?
Or shall I look in https://github.com/eliasgranderubio/dagda/blob/master/dagda/vulnDB/bid_downloader.py which is Apache-licensed?
Thanks!

**Comment by eliasgranderubio** [comment]
I've just add the License file to the repository which is Apache-2.0.

Regards.
